- examples/crd/main.tf
- examples/deployment/deployment.tf
- examples/ingress/ingress.tf
- examples/namespace/namespace.tf
- examples/pod/pod.tf
- examples/role/role.tf
- examples/service/service.tf
- examples/terraform-operator/sync-workspace-role.tf
- examples/terraform-operator/sync-workspace-rolebinding.tf
- examples/terraform-operator/sync-workspace-secret.tf
- examples/terraform-operator/sync-workspace-serviceaccount.tf
- examples/terraform-operator/sync-workspaces-deployment.tf
- examples/terraform-operator/variables.tf
- examples/terraform-operator/workspaces.app.terraform.io.tf
This change formats the example templates using `terraform fmt`
It also adds an example for a Service resource and complements the Pod example with env var attributes that have proven problematic in the past.
> Format examples

- scripts/build_release_binaries.sh
This change aims to fix the binary building script. 
Following a previous change to enable static binaries, the build script would fail with an error as not all platforms being built support static linking.
With this change, target platforms are separated into two groups. Ones that allow static builds are built as static binaries, while the rest are built as normal binaries with dynamic libc.
Tested by running the script locally on macOS
> Only build static binaries for platforms that support it

- GNUmakefile
👋  folks,
I was trying out the alpha provider and ran into issues due to the CI failures causing nightlies to not be up to date. I somewhat expected `make install` to install the provider into a usable place, and was surprised when it didn't.
Filling this to simplify the testing and installation workflow for others, but understand if you don't want to merge this and would rather folks build/copy manually.
> chore: install to terraforms plugin directory

- .github/workflows/release_binaries.yaml
- .goreleaser.yaml
Add hc-codesign back to the release workflow.
> Sign releases for MacOS and Windows

- provider/server.go
When providing the cluster credentials as output of another provider you currently get a panic as the value is unknown, this adds an extra check to avoid that which makes the provider accept the credentials.
Might not be the best way, feedback welcome!
> Add host.IsKnown() to avoid unknown value error

- README.md
- docs/index.md
Add full URLs so that links aren't broken when README is vaccumed up by registry. Also updates README installation instructions. Relates to #58 
> Update README with registry changes (#58)

- provider/server.go
When initializing the provider with username and password I received an "Unauthorized" error. Checking the log (dev.log) I noticed that the "Password" field was blank.
Setting the correct value AuthInfo value in "provider/server.go" should fix this problem.
> Fix login with username and password

- examples/cluster-with-resources/README.md
- examples/cluster-with-resources/cluster/test.tf
- examples/cluster-with-resources/main.tf
- examples/cluster-with-resources/manifests/test.tf
- provider/clients.go
- provider/resource_hcl.go
- provider/server.go
This change complements #65 and ensures that client instances are created as late as possible, right before the first API call needs to be made. 
In turn, this ensures that any incomplete transient credentials are not passed to the client, avoiding the consequent early failures.
Notably, this also fixes a provider failure mode where a missing kubeconfig file would cause Terraform to crash.
> Defer client initialization

- main.go
- provider/plugin.go
This change adds a command line argument to the provider binary to allow it to start in stand-alone mode and let Terraform connect to it during operations. This allows for easier debugging as one can attach a debugger to the provider process.
To start the provider in debug mode, run the provider binary with the `-debug` command line argument.
It should output a command that exports and environment variable, like so:
```
export TF_REATTACH_PROVIDERS='{"hashicorp/kubernetes-alpha":{"Protocol":"grpc","Pid":22668,"Test":true,"Addr":{"Network":"unix","String":"/var/folders/t7/z1g1xbgn4qzd6pck7d_s1zxh0000gn/T/plugin352167827"}}}'
```
To use the provider, copy the `export` statement and paste it in the shell session where you want to run `terraform`. You will then be able to run `terraform init` …
> Add standalone process debug mode

- .github/workflows/check_examples.yaml
- GNUmakefile
- main.go
- provider/plugin.go
- scripts/check_examples.sh
- test/acceptance/acceptance_test.go
This tidies up the reattach code so there is less duplication.
I have also fixed the check examples script and added a `check-examples` target to the Makefile.
```release-note
NONE
```
> Tidy up reattach code

- docs/resources/kubernetes_manifest.md
fixed a small typo in the docs: `Kubernete` -> `Kubernetes`
```release-note
NONE
```
> fix small typo in docs

- examples/vault/injector.tf
- examples/vault/main.tf
- examples/vault/webhook.tf
Update provider block and remove interpolation-only syntax.
Minor fixes to correct errors seen during `apply`.
```release-note
Update vault example to fix `apply` errors.
```
> Update vault example

- examples/vault/injector.tf
- examples/vault/server.tf
This allows the vault example to successfully apply using a pre-released version of terraform (at commit 55e6f64977b) and the `local-plan` branch of this repo.
```release-note
...
```
> Remove namespace from non-namespaced resources

- provider/configure.go
This change introduces a check for the minimum Terraform version required to run the provider reliably.
When used with an earlier version than 0.14.8, the provider will throw the following error:
```
» terraform plan                                                                                                          alex@Alexs-MBP
Error: Terraform version too old
on namespace.tf line 1, in provider "kubernetes-alpha":
1: provider "kubernetes-alpha" {
This provider requires a Terrafrom version starting at v0.14.8 and above
-----------------------------------------------------------------------
```
```release-note
ENHANCEMENTS:
* provider will now throw an error when used …
```
> Check min Terraform version used to call the provider

- provider/configure.go
This change fixes a few copy-paste errors in the provider configuration processing that resulted in `token`, `username` and `password` attributes not being handled correctly.
A side effect of this misconfiguration seems to have caused infinite request retrying on the discovery API.
This also changes the return statements in `ConfigureProvider` to not return an error when diagnostics are set. Returning an error would prevent the diagnostics from being displayed by Terraform.
```release-note
BUGFIXES:
* fix handling of `token`, `username` and `password` attributes in the provider configuration (#162)
* fix infinite retries on discovery API with invalid credentials (#159)
``` …
> Parse token in correct variable & return diagnostics not errors

- provider/validate.go
This change relaxes an error check during validation to accomodate for situations where attribute values can be unknown at this point.
Throwing an error here will prevent an eventually valid resource to reach the processing step where interpolations are resolved.
One particular situation that leads to this is when attribute values are set via Terraform's buit-in functions, which are evaluated later than ValidateResourceTypeConfig.
```release-note
* Don't fail validation when manifest contains unkown values (#169)
```
Fixes #169
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the …
> Don't fail validation when manifest contains unknown values

- .github/workflows/acceptance_tests.yaml
- .github/workflows/check_examples.yaml
- .github/workflows/unit_tests.yaml
This file had to be renamed to accommodate the release process, but I omitted to update these workflows on that occasions.
> Adapt github workflow to use new .go-version file name

- provider/clients.go
- provider/plan.go
This change introduces a check for valid credentials at the beginning of plan. This is to ensure that users get a clear meaningful error message rather than a raw error from the API.
If credentials are invalid but the API is otherwise accessible the users will get this message:
```
Error: Invalid credentials
on main.tf line 5, in resource "kubernetes_manifest" "test-configmap":
5: resource "kubernetes_manifest" "test-configmap" {
The credentials configured in the provider block are not accepted by the API
server. Error: Unauthorized
Set TF_LOG=debug and look for '[InvalidClientConfiguration]' in the log to see
actual configuration.
```
The check is performed by doing a simple GET call on the API endpoint using the path `/apis` which only responds to authenticated calls but otherwise …
> Do API request to validate access before plan

- go.mod
- go.sum
- vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/doc.go
- vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/attribute_path.go
- vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tftypes/value.go
- vendor/modules.txt
This provider depends on changes in terraform-plugin-go which have been in PR for a while and we're so far resorted to aggregating them in a fork.
Now that those changes are merged, we should re-align to the main plugin-go repository as a dependency. Note that a release hasn't been cut with said changes yet so we have to vendor on the commit from the tip of `main` branch.
```release-note
N/A
```
https://github.com/hashicorp/terraform-plugin-go/pull/58
https://github.com/hashicorp/terraform-plugin-go/pull/60
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help …
> Bump terraform-plugin-go

- morph/morph.go
- morph/morph_test.go
When morphing values from source to wireformat, which is uploaded to
Kubernetes, this plugin performs type coherence checking to ensure
you're not uploading "foo" into a field that expects a number.
Previously, if the value you were trying to pass was "Unknown", meaning
it was to be computed during the apply phase, you would get an error
about failing to morph from object element to object element. This is a
good error to have in place since it prevents the user from accidentally
passing an inappropriately typed value into the Kubernetes cluster and
doesn't even require communication with the cluster, making it decidable
very early in the execution flow.
This change modifies the algorithm to allow situations where you're not
dependent on type coercion to proceed. E.g. the "Unknown" value …
> Opportunistically accept unknown value types

- provider/apply.go
- provider/plan.go
- provider/read.go
- provider/resource.go
- test/acceptance/nonstructuredcustomresource_test.go
- test/acceptance/testdata/NonStructuredCustomResource/custom_resource.tf
- test/acceptance/testdata/NonStructuredCustomResource/variables.tf
- test/acceptance/testdata/NonStructuredCustomResourceDefinition/customresourcedefinition.tf
- test/acceptance/testdata/NonStructuredCustomResourceDefinition/variables.tf
- test/helper/kubernetes/kubernetes_helper.go
This PR brings in support for non-strucured CRDs, which currently error out when used with the provider.
Non-structured custom resources have CRDs which have an empty schema. This means their body outside of the metadata can be any arbitrary structure and we can't infer it from the OpenAPI spec for the cluster. In this case we make a best effort attempt to guess the type information from the config.
crd:
```hcl
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
name: dummies.k8s.terraform.us
spec:
group: k8s.terraform.us
version: v1alpha1
names:
kind: Dummy
plural: dummies
singular: dummy
scope: Namespaced
```
config:
```hcl
provider "kubernetes-alpha" {
config_path = "~/.kube/config"
}
resource "kubernetes_manifest" "dummy_test" {
provider = …
```
> Add support for non-structured custom resources

- morph/morph.go
- morph/morph_test.go
- payload/to_value.go
- payload/to_value_test.go
- test/acceptance/customresourcedefinition_test.go
- test/acceptance/testdata/CustomResourceDefinition/customresourcedefinition.tf
This change fixes the issues reported in https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/212
In particular, it corrects the handling of empty lists, sets and maps. 
It also corrects the morphing of object types so that attribute types are extracted from the morphed attributes' values rather than copied directly from the requested target type. This allows for elements containing morphed tuples (heterogeneous lists) to be correctly carried over in the result object after morphing (main issue reported in #212).
```release-note
BUG FIXES:
* CRDs with multiple versions now correctly handled again (#212)
* empty list and map attributes are now correctly …
```
> Fixes for empty lists, sets and maps and lists containing dynamicPseudoType

- provider/apply.go
Just a small typo we've found when getting a apply error 😄 
```NONE
...
```
> Fix typo in ApplyResourceChange

- test/acceptance/cronjob_test.go
- test/acceptance/daemonset_test.go
- test/acceptance/hpa_test.go
- test/acceptance/job_test.go
- test/acceptance/namespace_test.go
- test/acceptance/secret_test.go
- test/acceptance/statefulset_test.go
- test/acceptance/testdata/CronJob/cronjob.tf
- test/acceptance/testdata/CronJob/variables.tf
- test/acceptance/testdata/DaemonSet/daemonset.tf
- test/acceptance/testdata/DaemonSet/variables.tf
- test/acceptance/testdata/HPA/hpa.tf
- test/acceptance/testdata/HPA/hpa_modified.tf
- test/acceptance/testdata/HPA/variables.tf
- test/acceptance/testdata/Job/job.tf
- test/acceptance/testdata/Job/variables.tf
- test/acceptance/testdata/Namespace/namespace.tf
- test/acceptance/testdata/Namespace/namespace_modified.tf
- test/acceptance/testdata/Namespace/variables.tf
- test/acceptance/testdata/Secret/secret.tf
- test/acceptance/testdata/Secret/variables.tf
- test/acceptance/testdata/StatefulSet/statefulset.tf
- test/acceptance/testdata/StatefulSet/variables.tf
This PR adds acceptance tests for DaemonSet, StatefulSet, Job, CronJob, Secret, Namespace, and HPA.
```release-note
NONE
```
> Add more test coverage of basic resources

- .github/labeler-issue-triage.yml
- .github/labeler-pull-request-triage.yml
- .github/workflows/issue-comment-created.yml
- .github/workflows/issue-opened.yml
- .github/workflows/lock.yml
- .github/workflows/pull-request.yml
- .hashibot.hcl
GitHub HashiBot is being deprecated and this replaces behaviors with equivalent workflows in GitHub Actions. The `pull_request_size_labeler` behavior will be handled one an upstream enhancement is merged (or if we decide to use a fork with the change).
```release-note
NONE
```
Internal.
> Migrate most GitHub HashiBot behaviors to GitHub Actions

- .github/workflows/acceptance_tests.yaml
Add TF 1.0.0 to test matrix. Bump to 0.15.5
```release-note
...
```
> Add TF 1.0.0 to test matrix

- morph/morph.go
After exploring validation options in https://github.com/hashicorp/terraform-provider-kubernetes-alpha/pull/233, I found I could best support all valid use cases by using [ValidateValue](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-go@v0.3.0/tftypes#ValidateValue) prior to running [NewValue](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-go@v0.3.0/tftypes#NewValue).
From the docs:
```
If the passed value is not a valid value for the passed type, NewValue will panic. 
Any value and type combination that does not return an error from ValidateValue 
is guaranteed to not panic. When calling NewValue with user input with a type not
known at compile time, it is recommended to call ValidateValue before calling
NewValue, to allow graceful handling of the error.
```
This will …
> Use tftypes ValidateValue to catch panics
